# Generated by Django 4.1.5 on 2023-02-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photosApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='imagem',
            field=models.ImageField(upload_to='photosApi/imagens/%Y/%m/%d/'),
        ),
    ]
