# Generated by Django 4.1.5 on 2023-01-31 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorsmodel',
            name='fullname',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='authorsmodel',
            name='email',
            field=models.EmailField(error_messages={'unique': 'O email cadastrado já existe.'}, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='authorsmodel',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
