# Generated by Django 4.1.5 on 2023-02-07 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_alter_authorsmodel_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorsmodel',
            name='is_superuser',
            field=models.BooleanField(default=True),
        ),
    ]
